services:
  - type: web
    name: 2d3d-lottery-api
    env: php
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: db_2d3d_lottery_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: db_2d3d_lottery_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: db_2d3d_lottery_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: db_2d3d_lottery_db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: db_2d3d_lottery_db
          property: password
      - key: APP_ENV
        value: production

databases:
  - name: db_2d3d_lottery_db
    databaseName: db_2d3d_lottery_db
    user: db_2d3d_lottery_db_user
    plan: free
