services:
  - type: web
    name: 2d3d-lottery-api
    env: php
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DB_HOST
        value: dpg-ctm70o9opnds73fdciig-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: db_2d3d_lottery_db
      - key: DB_USER
        value: db_2d3d_lottery_db_user
      - key: DB_PASS
        value: ZcV5s0MAJrFxPyYfQFr7lJFADwxFAn6b
      - key: APP_ENV
        value: production
      - key: SITE_URL
        value: https://twod3d-lottery.onrender.com
      - key: API_URL
        value: https://twod3d-lottery-api-q68w.onrender.com

databases:
  - name: db_2d3d_lottery_db
    databaseName: db_2d3d_lottery_db
    user: db_2d3d_lottery_db_user
    plan: free
